freebsd_instance:
  image_family: freebsd-11-3-snap

task:
  install_script: pkg install -y git gmake go bash
  script: cd filebeat && GOPATH=$(pwd)/../.. gmake
  binaries_artifacts:
    path: "filebeat/filebeat"
